routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'auth.user'])->group(function() {
    Route::get('/requests', 'RequestController@index')->name('requests.index');
    Route::get('/requests/create', 'RequestController@create')->name('requests.create');
    Route::get('/requests/{id}', 'RequestController@show')->name('requests.show');
    Route::post('/requests', 'RequestController@store')->name('requests.store');
    Route::delete('/requests/{id}', 'RequestController@destroy')->name('requests.destroy');
}); 

Route::prefix('manager')->name('manager.')->middleware(['auth', 'auth.manager'])->group(function () {
    Route::get('requests', 'ManagerRequestController@index')->name('requests.index');
});

Route::prefix('manager')->name('manager.')->middleware(['auth.jwt'])->group(function () {
    Route::get('requests/{id}', 'ManagerRequestController@show')->name('requests.show');
    Route::post('requests/{id}/answer', 'ManagerRequestController@answer')->name('requests.answer');
    Route::post('requests/{id}/accept', 'ManagerRequestController@accept')->name('requests.accept');
});

Route::get('/storage/app/uploads/{fileName}', function($fileName) {
    $destinationPath = base_path() . "/storage/app/uploads/" . $fileName;
    return response()->download($destinationPath);
});

app/Request.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    protected $fillable = ['title', 'message', 'parent_id'];

    public function user() 
    {
        return $this->belongsTo('App\User');
    }

    public function scopeToday($query, $id)
    {
        return $query->whereDate('created_at', Carbon::today())
            ->where('user_id', $id);
    }

    public function scopeFilter($query, $viewed, $hasAnswer, $status, $accepted) 
    {
        if(count($viewed) == 1) {
            $viewed = self::stringToBool($viewed[0]);
            $query = $query->where('viewed', '=', $viewed);
        }

        if(count($hasAnswer) == 1) {
            $hasAnswer = self::stringToBool($hasAnswer[0]);
            $query = $query->where('has_answer', '=', $hasAnswer);
        }

        if(count($status) == 1) {
            $query = $query->where('status', '=', $status);
        }

        if(count($accepted) == 1) {
            $accepted = self::stringToBool($accepted[0]);

            if($accepted) {
                $query = $query->where('manager_id', '!=', NULL);
            } else {
                $query = $query->whereNull('manager_id');
            }
            
        }

        return $query;
    }

    public static function stringToBool($value)
    {
        return (int)filter_var($value, FILTER_VALIDATE_BOOLEAN);
    }
}

app/Http/Controllers/RequestController.php
<?php

namespace App\Http\Controllers;

use App\User;
use JWTAuth;
use Illuminate\Http\Request;
use App\Request as UserRequest;
use Illuminate\Support\Facades\Auth;
use App\Notifications\RequestClosed;
use App\Notifications\RequestCreated;
use App\Http\Requests\StoreRequest as StoreRequest;

class RequestController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $userRequests = $user->requests()->orderBy('id', 'DESC')->get();

        return view('request.index', ['userRequests' => $userRequests]);
    }

    public function create()
    {
        return view('request.create');
    }

    public function store(StoreRequest $request)
    {
        $user = Auth::user();
        $userRequest = new UserRequest();
        $todayRequest = $userRequest->today($user->id)->first();

        if($todayRequest) {
            return back()->withInput()
                ->with('error_message', __('site.request.today.exist.error'));
        }

        if(null !== $request->file('uploads')) {
            $filePath = $request->file('uploads')->store('uploads');
            $userRequest->uploads = $filePath;
        }

        if($request->parent_id) {
            $parentRequest = (new UserRequest())->find($request->parent_id);
            $parentManagerId = $parentRequest->manager_id;
        }

        if(isset($parentManagerId)) {
            $userRequest->manager_id = $parentManagerId;
        }

        $userRequest->fill($request->all());
        $userRequest->user()->associate($user);
        $userRequest->save();

        if(!isset($parentManagerId)) {
            $managers = (new User())->where('role', 'manager')->get();

            foreach($managers as $manager) {
                $token = JWTAuth::fromUser($manager);
                $manager->notify(new RequestCreated($userRequest, $request->file('uploads') ?? null, $token));
            }
        } else {
            $manager = (new User())->find($parentManagerId);
            $token = JWTAuth::fromUser($manager);
            $manager->notify(new RequestCreated($userRequest, $request->file('uploads') ?? null, $token));
        }

        return redirect()->route('requests.index');
    }

    public function show($id)
    {
        $userRequest = (new UserRequest())->find($id);
        if(!$userRequest) {
            abort(404);
        }

        return view('request.show', ['userRequest' => $userRequest]);
    }

    public function destroy($id)
    {
        $user = Auth::user();

        $userRequest = (new UserRequest())->with('user')->find($id);
        $userRequest->status = 'closed';
        $userRequest->save();

        $manager = (new User())->find($userRequest->manager_id);

        if($manager) {
            $manager->notify(new RequestClosed($user, $userRequest));
        }
    }
}

resources/views/manager/request/index.blade.php
@extends('layouts.app')

@section('content')
    <form id="filter-form">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="viewed" name="viewed[]" value="true"
            @if(isset($_GET['viewed']) && in_array("true", $_GET['viewed'])) ? checked @endif>
            <label class="form-check-label" for="viewed">{{__('site.manager.requests.viewed')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="not-viewed" name="viewed[]" value="false"
            @if(isset($_GET['viewed']) && in_array("false", $_GET['viewed'])) ? checked @endif>
            <label class="form-check-label" for="not-viewed">{{__('site.manager.requests.not.viewed')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="has-answer" name="has_answer[]" value="true"
            @if(isset($_GET['has_answer']) && in_array("true", $_GET['has_answer'])) ? checked @endif>
            <label class="form-check-label" for="has-answer">{{__('site.manager.requests.has.answer')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="has-no-answer" name="has_answer[]" value="false"
            @if(isset($_GET['has_answer']) && in_array("false", $_GET['has_answer'])) ? checked @endif>
            <label class="form-check-label" for="has-no-answer">{{__('site.manager.requests.has.no.answer')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="open" name="status[]" value="active"
            @if(isset($_GET['status']) && in_array("active", $_GET['status'])) ? checked @endif>
            <label class="form-check-label" for="open">{{__('site.manager.requests.active')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="closed" name="status[]" value="closed"
            @if(isset($_GET['status']) && in_array("closed", $_GET['status'])) ? checked @endif>
            <label class="form-check-label" for="closed">{{__('site.manager.requests.closed')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="accepted" name="accepted[]" value="true"
            @if(isset($_GET['accepted']) && in_array("true", $_GET['accepted'])) ? checked @endif>
            <label class="form-check-label" for="closed">{{__('site.manager.requests.accepted')}}</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="accepted" name="accepted[]" value="false"
            @if(isset($_GET['accepted']) && in_array("false", $_GET['accepted'])) ? checked @endif>
            <label class="form-check-label" for="closed">{{__('site.manager.requests.not.accepted')}}</label>
        </div>
    </form>

    <table class="table table-striped" style="width: 1000px">
        <thead class="thead-dark">
            <tr>
                <th>created_at</th>
                <th>user_name</th>
                <th>title</th>
                <th>status</th>
                <th>viewed</th>
                <th>has_answer</th>
                <th>assign_to_me</th>
            </tr>
        <thead>
        <tbody>
        @forelse($userRequests as $request)
        <tr>
            <td>{{ $request->created_at }}</td>
            <td>{{ $request->user->name }}</td>
            <td><a href="{{ route('manager.requests.show', ['id' => $request->id]) }}">{{ $request->title }}</a></td>
            <td>{{ $request->status }}</td>
            <td>{{ $request->viewed ? __('site.manager.request.viewed') : '' }}</td>
            <td>{{ $request->has_answer ? __('site.manager.request.has.answer') : '' }}</td>
            <td>{{ ($request->manager_id == Auth::user()->id) ? __('site.yes') : '' }}</td>
        </tr>
        @empty
            <p>{{__('site.manager.requests.empty')}}</p>
        @endforelse
        </tbody>
    </table>
@endsection

<script src="{{ asset('js/manager-index.js') }}" defer></script>

resources/views/manager/request/show.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('manager.requests.index') }}">{{__('site.create.back')}}</a>

    <table class="table table-striped" style="width: 1000px">
        <tr><td>{{ __('site.username') }}:</td><td>{{ $userRequest->user->username }}</td></tr>
        <tr><td>{{ __('site.email') }}:</td><td>{{ $userRequest->user->email }}</td></tr>
        <tr><td>{{ __('site.create.lable.title') }}:</td><td>{{ $userRequest->title }}</td></tr>
        <tr><td>{{ __('site.create.lable.message') }}:</td><td>{{ $userRequest->message }}</td></tr>
        <tr><td>{{ __('site.uploads') }}:</td><td><a href="{{ asset('storage/app/' . $userRequest->uploads) }}" download>{{ $userRequest->uploads }}</a></td></tr>
    </table>

    @if(!isset($userRequest->manager_id)) 
        <input type="hidden" id="accept-url" value="{{ route('manager.requests.accept', ['id' => $userRequest->id]) }}">
        <button type="button" id="accept" class="btn btn-success">{{__('site.manager.request.accept.btn')}}</button>
    @endif

    @if(isset($userRequest->manager_id) && $userRequest->manager_id == Auth::user()->id)
        <form action="{{ route('manager.requests.answer', ['id' => $userRequest->id]) }}" method="post" id="requests-answer" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="message">{{__('site.create.lable.message')}}</label>
                <textarea type="message" name="message" class="form-control" required id="message">{{ old('message') }}</textarea>
                @if ($errors->has('message'))
                    <div class="alert alert-danger">
                        {{ $errors->first('message') }}
                    </div>
                @endif
            </div>
            <input type="submit" class="btn btn-success btn-lg w-100" value="{{__('site.create.submit.btn')}}">
        </form>
    @endif    
@endsection

<script src="{{ asset('js/ajax.js') }}" defer></script>
<script src="{{ asset('js/manager-show.js') }}" defer></script>